#!/bin/bash

read -p "Do you wish to install PHP 5.6 (y/n)?" answer

function tools {
    wget https://phar.phpunit.de/phploc.phar && \
        chmod +x phploc.phar && \
        sudo mv phploc.phar /usr/local/bin/phploc && \
    wget http://static.pdepend.org/php/latest/pdepend.phar && \
        chmod +x pdepend.phar && \
        sudo mv pdepend.phar /usr/local/bin/pdepend && \
    wget http://static.phpmd.org/php/latest/phpmd.phar && \
        chmod +x phpmd.phar && \
        sudo mv phpmd.phar /usr/local/bin/phpmd && \
    wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar && \
        chmod +x phpcs.phar && \
        sudo mv phpcs.phar /usr/local/bin/phpcs && \
    wget https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar && \
        chmod +x phpcbf.phar && \
        sudo mv phpcbf.phar /usr/local/bin/phpcbf && \
    wget https://phar.phpunit.de/phpcpd.phar && \
        chmod +x phpcpd.phar && \
        sudo mv phpcpd.phar /usr/local/bin/phpcpd && \
    wget https://phar.phpunit.de/phpdcd.phar && \
        chmod +x phpdcd.phar && \
        sudo mv phpdcd.phar /usr/local/bin/phpdcd && \
    wget https://github.com/Halleck45/PhpMetrics/raw/master/build/phpmetrics.phar && \
        chmod +x phpmetrics.phar && \
        sudo mv phpmetrics.phar /usr/local/bin/phpmetrics && \
    wget http://get.sensiolabs.org/php-cs-fixer.phar && \
        chmod +x php-cs-fixer.phar && \
        sudo mv php-cs-fixer.phar /usr/local/bin/php-cs-fixer
}

case $answer in
    y|Y )
        sudo add-apt-repository ppa:ondrej/php
        sudo apt-get update
        sudo apt-get install php5.6 php5.6-xml
        tools
    ;;
    * )
        read -p "Do you wish to install PHP 7.0 (y/n)?" answer

        case $answer in
            y|Y )
                sudo apt-get update
                sudo apt-get install php7.0 php7.0-xml
                tools
            ;;
            * )
                echo "PHP not installed"
            ;;
        esac
    ;;
esac

