#!/bin/bash

function tools {
    wget --no-check-certificate https://phar.phpunit.de/phploc.phar && \
        chmod +x phploc.phar && \
        sudo mv phploc.phar /usr/local/bin/phploc && \
    wget --no-check-certificate http://static.pdepend.org/php/latest/pdepend.phar && \
        chmod +x pdepend.phar && \
        sudo mv pdepend.phar /usr/local/bin/pdepend && \
    wget --no-check-certificate http://static.phpmd.org/php/latest/phpmd.phar && \
        chmod +x phpmd.phar && \
        sudo mv phpmd.phar /usr/local/bin/phpmd && \
    wget --no-check-certificate https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar && \
        chmod +x phpcs.phar && \
        sudo mv phpcs.phar /usr/local/bin/phpcs && \
    wget --no-check-certificate https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar && \
        chmod +x phpcbf.phar && \
        sudo mv phpcbf.phar /usr/local/bin/phpcbf && \
    wget --no-check-certificate https://phar.phpunit.de/phpcpd.phar && \
        chmod +x phpcpd.phar && \
        sudo mv phpcpd.phar /usr/local/bin/phpcpd && \
    wget --no-check-certificate https://phar.phpunit.de/phpdcd.phar && \
        chmod +x phpdcd.phar && \
        sudo mv phpdcd.phar /usr/local/bin/phpdcd && \
    wget --no-check-certificate https://github.com/Halleck45/PhpMetrics/raw/master/build/phpmetrics.phar && \
        chmod +x phpmetrics.phar && \
        sudo mv phpmetrics.phar /usr/local/bin/phpmetrics && \
    wget --no-check-certificate http://get.sensiolabs.org/php-cs-fixer.phar && \
        chmod +x php-cs-fixer.phar && \
        sudo mv php-cs-fixer.phar /usr/local/bin/php-cs-fixer && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
        php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
        php composer-setup.php && \
        php -r "unlink('composer-setup.php');" && \
        sudo mv composer.phar /usr/local/bin/composer
}

read -p "Do you wish to install PHP 5.6 (y/n)?" answer
case $answer in
    y|Y )
        sudo add-apt-repository ppa:ondrej/php
        sudo apt-get update
        sudo apt-get install php5.6 php5.6-xml
    ;;
    n|N )
        read -p "Do you wish to install PHP 7.0 (y/n)?" answer

        case $answer in
            y|Y )
                sudo apt-get update
                sudo apt-get install php7.0 php7.0-xml
            ;;
            n|N )
                echo "PHP not installed"
            ;;
        esac
    ;;
esac

read -p "Do you wish to install PHP tools (y/n)?" answer
case $answer in
    y|Y )
        tools
    ;;
    n|N )
        echo "PHP tools not installed"
    ;;
esac

