#!/bin/bash

# install vim dependencies

# for ack.vim
sudo apt-get install ack-grep

# for neocomplete
sudo apt-get install vim-nox

# for phpcd.vim
cd ~/dotfiles/vim/bundle/phpcd.vim
composer install
cd ~/dotfiles

# for tagbar
cd ~/dotfiles/universal-ctags
sudo apt-get install pkg-config
sudo apt-get install autoconf
#sudo apt-get install checkinstall
./autogen.sh
./configure
make
#sudo checkinstall
sudo make install
cd ~/dotfiles
