#!/bin/bash

# install vim dependencies

# for ack.vim
sudo apt-get install ack-grep

# for neocomplete
sudo apt-get install vim-nox

# for tagbar
cd ~/dotfiles/universal-ctags
sudo apt-get install pkg-config
sudo apt-get install autoconf
sudo apt-get install checkinstall
./autogen.sh
./configure
make
sudo checkinstall
cd ~/dotfiles
